### ISSUE TITLE
dotnet-uninstall-tool Roadmap

### ISSUE THREAD

**Issue by baronfel** [dotnet/cli-lab#279]
Hello everyone - this issue captures the roadmap for the dotnet-uninstall-tool for the near future. This tool serves an important purpose (especially for our macOS users) and it has been left to linger a bit too long.  We're going to take some actions in the short- and long-term to unblock users for .NET 8 today, and make maintenance easier on the team.

The short-term actions we're going to take are:
* [x] Review, merge #268 to allow users to manage .NET 8 tools on their machines
* [x] Update the TFM of the tool from `netcoreapp3.1` to `net8.0` in #280, and the local SDK to .NET 8
* [x] Fix the way the application's assemblies are signed to ensure that all assemblies that are part of the app are in fact signed: https://github.com/dotnet/cli-lab/pull/281, https://github.com/dotnet/cli-lab/pull/282
* [ ] test and release the .NET 8-compatible version
* [ ] Update the build pipelines of this repo to align with some internal engineering changes

We believe these things will unblock users and get us on a good path for building and releasing this tool. However, there are some additional maintenance hurdles that we need to handle in a couple months, after these first items are done:

* [ ] Remove the version upper bound restriction that prevents users from using the tool to manage newer toolsets than we explicitly coded for
* [ ] Update the dependencies used in the tool to ensure we pick up bugfixes

We hope this plan helps clarify what to expect from the tool, as well as sets us up for success in the future.

**Comment by baronfel** [comment]
A bit of an update on this - we've done quite a bit of work on greening up this repository, but the first round of testing has logged a few issues we need to triage. We're currently working through some internal engineering tasking that we have to do first, but will be coming back to this afterwards.

**Comment by baronfel** [comment]
We're through the internal engineering tasks and are doing validation/testing of the tool. Once we have results from that, if things are looking good we'll be ready to release :)

**Comment by baronfel** [comment]
We've now released a new version of the tool that supports managing .NET 8 installs. Please see the [release notes](https://github.com/dotnet/cli-lab/releases/tag/1.7.521001) for more details!
